### ISSUE TITLE
combine from a Hash (?)

### ISSUE THREAD

**Issue by waiting-for-dev** [rom-rb/rom#293] opened 2015-07-30 08:34 UTC
I'm trying to use rom in order to migrate data from a legacy database to a new one.

In the legacy database I have one single table `clients`, which have both client and address information for the client, while in the new database I have two tables `clients` and `addresses`, related with a foreign key.

For the new database `clients` mapper I'm using `combine` method in the following way:

    module Destination
      # Destination client mapper
      class Client < ROM::Mapper
        register_as :destination_client
        relation :destination_clients

        reject_keys true
        symbolize_keys

        attribute :name
        attribute :identifier

        combine :address, on: { address_id: :id }, type: :hash do
          attribute :address
        end
      end
    end

In the legacy database `clients` mapper, I'm wrapping `address` in the following way:

    module Origin
      # Origin client mapper
      class Client < ROM::Mapper
        register_as :origin_client
        relation :origin_clients

        reject_keys true
        symbolize_keys

        attribute :name
        attribute :identifier

        wrap :address do
          attribute :address
        end
      end
    end

I have checked and doing:

    rom.relation(:origin_clients).as(:origin_client).to_a
    rom.relation(:destination_clients).combine(addresses.for_clients).as(:destination_client)

works as expected.

Now, I'm trying to populate destination mapper as explained in post [Importing data with rom and transproc](http://solnic.eu/2015/07/15/importing-data-with-rom-and-transproc.html).

    data_origin = rom.relation(:origin_clients).as(:origin_client).to_a
    data_destination = Destination::Client.build.call(data_origin)

But I get following error:

    no implicit conversion of Symbol into Integer
    /home/marc/.gem/ruby/2.2.2/gems/transproc-0.3.0/lib/transproc/array.rb:163:in `values_at'
    /home/marc/.gem/ruby/2.2.2/gems/transproc-0.3.0/lib/transproc/array.rb:163:in `block (2 levels) in combine'
    /home/marc/.gem/ruby/2.2.2/gems/transproc-0.3.0/lib/transproc/array.rb:152:in `each'
    /home/marc/.gem/ruby/2.2.2/gems/transproc-0.3.0/lib/transproc/array.rb:152:in `each_with_index'
    /home/marc/.gem/ruby/2.2.2/gems/transproc-0.3.0/lib/transproc/array.rb:152:in `block in combine'
    /home/marc/.gem/ruby/2.2.2/gems/transproc-0.3.0/lib/transproc/array.rb:149:in `each'
    /home/marc/.gem/ruby/2.2.2/gems/transproc-0.3.0/lib/transproc/array.rb:149:in `map'
    /home/marc/.gem/ruby/2.2.2/gems/transproc-0.3.0/lib/transproc/array.rb:149:in `combine'
    /home/marc/.gem/ruby/2.2.2/gems/transproc-0.3.0/lib/transproc/function.rb:47:in `[]'
    /home/marc/.gem/ruby/2.2.2/gems/transproc-0.3.0/lib/transproc/function.rb:47:in `call'
    /home/marc/.gem/ruby/2.2.2/gems/transproc-0.3.0/lib/transproc/composite.rb:30:in `call'
    /home/marc/.gem/ruby/2.2.2/gems/rom-0.8.1/lib/rom/mapper.rb:100:in `block in call'
    /home/marc/.gem/ruby/2.2.2/gems/rom-0.8.1/lib/rom/mapper.rb:100:in `each'
    /home/marc/.gem/ruby/2.2.2/gems/rom-0.8.1/lib/rom/mapper.rb:100:in `reduce'
    /home/marc/.gem/ruby/2.2.2/gems/rom-0.8.1/lib/rom/mapper.rb:100:in `call'

Is it possible to take data from a Hash and map to a mapper which is using `combine`?

Thanks

**Comment by solnic** [comment] 2015-07-30 18:31
If you already have a nested input there's no need to map it further. Just define a command that takes a client with nested address and that's it. Combine transformation is used to join parent and its child collections in memory using provided join keys. Typically you use it for eager-loading of associations.

Anyhow, something like that should work:

``` ruby
class CreateClient < ROM::Commands::Create[:sql]
  relation :clients
  result :one
end

class CreateAddress < ROM::Commands::Create[:sql]
  relation :clients
  result :one

  associates :client, key: [:client_id, :id]
end

create_client_with_address = rom.command([
  { client: :clients }, [:create, [{ address: :addresses }, :create]]
])

create_client_with_address.call(
  client: { name: 'a', identifier: 'b', address: { address: 'some address' } }
)
```

Lemme know if that works.

**Comment by waiting-for-dev** [comment] 2015-07-31 09:00
Many thanks for your response.

I was begining to smell redundance in that second mapper :) Anyway, for someone who could be interested in mapping from a nested hash, `embedded` did the trick.

So, just out of curiosity, is `combined` in mapper API tied to relational databases?

Now, about my problem. First, just a detail, my foreign key is in `client` and not in `address`, because there is another model which can share addresses with clients.

So, following your advice, here they are my commands:

```ruby
class CreateAddress < ROM::Commands::Create[:sql]
  relation :destination_addresses
  register_as :create

  result :one
end

class CreateClient < ROM::Commands::Create[:sql]
  relation :destination_clients
  register_as :create

  result :one

  associates :address, key: [:address_id, :id]
end
```

And here it is how I'm trying to do:

```ruby
clients_data = rom.relation(:origin_clients).as(:client).to_a
create_client_with_address = rom.command([
  { address: :destination_addresses }, [:create, [{ client: :destination_clients }, :create]]
])
clients_data.each do |data|
  # One example data:
  #
  # {:name=>"Some dummy name", :identifier=>1, :address=>{:address=>"Some dummy address", :zip=>"A_zip", :town=>"A town", :region=>"A region", :created_at=>2015-07-31 10:41:08 +0200, :updated_at=>2015-07-31 10:41:08 +0200}}
  create_client_with_address.call(client: data)
end
```

(Later I'll try to do it in one step, instead of iterating, but now I'm not worrying about it).

But I'm getting this error, complaining about missing `address` key:

```ruby
ROM::CommandFailure: command: #<ROM::Commands::Lazy:0xb1e0683c @command=#<RagasMigration::Commands::CreateAddress relation=#<RagasMigration$
:Relations::Destination::Addresses dataset=#<Sequel::Postgres::Dataset: "SELECT * FROM \"addresses\"">> options={:input=>Hash, :validator=>$
<Proc:0xb9a1287c@/home/marc/.gem/ruby/2.2.2/gems/rom-0.8.1/lib/rom/command.rb:15>, :result=>:one, :curry_args=>[]}>, @evaluator=#<Proc:0xb1$
06878@/home/marc/.gem/ruby/2.2.2/gems/rom-0.8.1/lib/rom/commands/graph/class_interface.rb:38 (lambda)>>; original message: command: #<ROM::$
ommands::Lazy:0xb1e0683c @command=#<RagasMigration::Commands::CreateAddress relation=#<RagasMigration::Relations::Destination::Addresses da$
aset=#<Sequel::Postgres::Dataset: "SELECT * FROM \"addresses\"">> options={:input=>Hash, :validator=>#<Proc:0xb9a1287c@/home/marc/.gem/ruby$
2.2.2/gems/rom-0.8.1/lib/rom/command.rb:15>, :result=>:one, :curry_args=>[]}>, @evaluator=#<Proc:0xb1e06878@/home/marc/.gem/ruby/2.2.2/gems$
rom-0.8.1/lib/rom/commands/graph/class_interface.rb:38 (lambda)>>; original message: key not found: :address
/home/marc/.gem/ruby/2.2.2/gems/rom-0.8.1/lib/rom/commands/graph/class_interface.rb:47:in `fetch'
/home/marc/.gem/ruby/2.2.2/gems/rom-0.8.1/lib/rom/commands/graph/class_interface.rb:47:in `block (2 levels) in build_command'
/home/marc/.gem/ruby/2.2.2/gems/rom-0.8.1/lib/rom/commands/graph/class_interface.rb:47:in `each'
/home/marc/.gem/ruby/2.2.2/gems/rom-0.8.1/lib/rom/commands/graph/class_interface.rb:47:in `reduce'
/home/marc/.gem/ruby/2.2.2/gems/rom-0.8.1/lib/rom/commands/graph/class_interface.rb:47:in `block in build_command'
/home/marc/.gem/ruby/2.2.2/gems/rom-0.8.1/lib/rom/commands/lazy.rb:37:in `[]'
/home/marc/.gem/ruby/2.2.2/gems/rom-0.8.1/lib/rom/commands/lazy.rb:37:in `call'
/home/marc/.gem/ruby/2.2.2/gems/rom-0.8.1/lib/rom/commands/graph.rb:54:in `call'
/home/marc/projects/clients_webs/ragas_migration/Rakefile:18:in `block (4 levels) in <top (required)>'
/home/marc/projects/clients_webs/ragas_migration/Rakefile:17:in `each'
/home/marc/projects/clients_webs/ragas_migration/Rakefile:17:in `block (3 levels) in <top (required)>'
```

**Bonus:** In fact I have two problems, because it seems that attribues inside a `wrap` block override and let without effect attributes with the same name outside the `wrap` block. I state this here because maybe it is just a silly thing done by me, but if it is an unrelated bug tell me and I'll open another separated issue.

My mapper is:

```ruby
class Client < ROM::Mapper
    register_as :client
    relation :origin_clients

    reject_keys true
    symbolize_keys

    attribute :name
    attribute :identifier, from: :id
    attribute(:created_at) { Time.now }
    attribute(:updated_at) { Time.now }

    wrap :address do
      attribute :address
      attribute :zip, from: :codigo_postal
      attribute :town, from: :poblacion
      attribute :region, from: :provincia
      attribute(:created_at) { Time.now }
      attribute(:updated_at) { Time.now }
    end
  end
end
```

But as you can see I'm not getting top level `created_at` and `updated_at`, but just the ones inside `address` wrap:

      {:name=>"Some dummy name", :identifier=>1, :address=>{:address=>"Some dummy address", :zip=>"A_zip", :town=>"A town", :region=>"A region", :created_at=>2015-07-31 10:41:08 +0200, :updated_at=>2015-07-31 10:41:08 +0200}}

Again, many thanks for your help. If it is getting a thing to be discussed outside github issues, please tell me how I can reach you.

**Comment by nepalez** [comment] 2015-07-31 09:16
@waiting-for-dev Concerning your last update.

The problem is that wrap operation removes from root those attributes, that have been wrapped. There is no way to wrap attributes and add their substitutes (under the same name) at once (in one step).

As a solution I'd propose doing this in 2 steps (though it is ~2 times slower):

```ruby
class Client < ROM::Mapper
    register_as :client
    relation :origin_clients

    reject_keys true
    symbolize_keys

    step do
      attribute :name
      attribute :identifier

      wrap :address do
        attribute :address
        attribute :zip
        attribute :town
        attribute :region
        attribute(:created_at) { Time.now }  # this will remove attributes from root
        attribute(:updated_at) { Time.now } # and this is too
      end
    end
  end

  step do
    attribute(:created_at) { Time.now }  # now we restore them at the root
    attribute(:updated_at) { Time.now }
  end
end
```

**Comment by solnic** [comment] 2015-07-31 09:53
I would also recommend not using `reject_keys` since data are coming from *your relations* that you can trust.

Regarding composed commands - the input needs to have `:address` in the root if you configured `{ address: :destination_address }` as it means "there will be `:address` key with its attributes and handle it use `destination_address` relation.

This is the latest addition to the API so as you can see error handling is pretty rough :) It's high on my priority list to improve it as I rely on it heavily already.

**Comment by waiting-for-dev** [comment] 2015-07-31 11:43
Thanks a lot both for your help.

About `wrap` option. Do you think that this should be the behaviour? I understand the logic about removing it from top level and nesting it, but I think it is not a too weird use case willing to have two attributes with the same name in both levels, even if one of them is not actually mapped but generated on-the-fly.

About my problem... I changed my mapper to wrap both `address` and `client` in order to have both at top level (by the way, doing so I can have both `created_at` attributes):

```ruby
class Client < ROM::Mapper
  register_as :client
  relation :origin_clients

  symbolize_keys

  wrap :client do
    attribute :name
    attribute :identifier
    attribute(:created_at) { Time.now }
    attribute(:updated_at) { Time.now }
  end

  wrap :address do
    attribute :address
    attribute :zip
    attribute :town
    attribute :region
    attribute(:created_at) { Time.now }
    attribute(:updated_at) { Time.now }
  end
end
```

Now, command:

```ruby
rom.command([
    { address: :destination_addresses }, [:create, [{ client: :destination_clients }, :create]]
    ])
```

successfully creates first address but then it fails with `KeyError: key not found: :client`.

Does that syntax in `command` mean that `client` key must be nested within `address`? I have tried this, but then sql statement fails with underfined column client for addresses table.

Many thanks.

**Comment by solnic** [comment] 2015-07-31 12:47
Yes, you need to wrap client inside address because the structure of the input defines hierarchy, so if client has an address it means it must be nested inside address hash.

Unfortunately for now you need to explicitly define input for commands so that it will reject those extra keys coming from combine commands, I consider it a bug and will fix it soon, commands should skip those keys automatically, so for now do this:

``` ruby
class CreateClient < ROM::Commands::Create[:sql]
  class Attributes
    include ROM::Model::Attributes # this comes from rom-rails
    attribute :name
    attribute :identifier
  end

  input Attributes

  relation :destination_clients
  register_as :create

  result :one

  associates :address, key: [:address_id, :id]
end
```

This will only accept specified keys, it's more like a workaround for now. I'll improve that in 0.8.2. Now I have even bigger motivation :)

**Comment by waiting-for-dev** [comment] 2015-07-31 13:41
Hey, many, many thanks again :)

Now, it is working :D

Just two considerations to let you know:

* I know that having `Model` in `rom-rails` gem is temporary, but, for the sake of information, I have had to also add `activemodel` in my gemspec file and require it just before `rails/model`.

* Finally, I have to use two `step` in my model (are you still sure that this shouldn't be considered a bug or feature request? :D). Also, I can't get a hash like `{ address: ... {client: ...} }`, because then my mapper should have:

```ruby
step do
  wrap(:address) do
    attribute :address

    wrap(:client) do
      attribute :address
      attribute(:created_at) { Time.now }
    end
  end
end

step do
  wrap(:address) do
    attribute(:created_at) { Time.now }
  end
end
```

which would result in `address` attribute for `address` key being nil. So I had to ride off top `wrap` and add it in my command call:

```ruby
create_client_with_address.call(address: data) 
```

Again, many thanks. I'm very grateful of "top names" like you not being vain and helping less experienced developers. I have been waiting for rom for a long time, I think it is one of the best things that can happen to ruby right now (it needs it, mainly rails).

**Comment by solnic** [comment] 2015-07-31 13:58
Awesome to know it worked for you :) Sorry about the quirks, I'll be fixing / improving things in next releases.

Regarding require issues - I gotta fix that, there's a big emphasis put in ROM on proper requires so that each component should be "requireable" separately.

As far as multi-step wrap goes, you only need wrap once, in the second step you can access wrapped address with `embedded :address, type: :hash { attribute(:created_at) { Time.now } }` **BUT** I would recommend setting default values inside commands as its closer to the database. `Model::Attributes` supports `timestamps` macro that will do it for you.

As a general rule I try to keep mappers only concerned about the structure of the output, setting values feels to close to the domain or db.

I'm always happy to provide help, thanks for the kind words :)

**Comment by solnic** [comment] 2015-07-31 13:58
ps. I reported #294 about that require problem in rom/model

**Comment by waiting-for-dev** [comment] 2015-07-31 14:05
Ok, thanks about the `embedded` tip, I'll do it. Also I'll check about setting default values in the commands, I have to look closer to the commands API. But it makes all the sense :)

**Comment by solnic** [comment] 2015-08-10 21:26
I hope things are working well for you. Gonna close this one for now. Please report issues if you have trouble with anything.

**Closed by solnic** 2015-08-10 21:26 UTC
